export const SHOP_REQUEST = 'shop/SHOP_REQUEST';
export const SHOP_SUCCESS = 'shop/SHOP_SUCCESS';
export const SHOP_FAILED = 'shop/SHOP_FAILED';
export const SHOP_CHOOSE_PAGE = 'shop/SHOP_CHOOSE_PAGE';
export const SHOP_CHOOSE_SORTBY = 'shop/SHOP_CHOOSE_SORTBY';
export const SHOP_CHOOSE_CATEGORY = 'shop/SHOP_CHOOSE_CATEGORY';
export const SHOP_INIT_LIST_PRODUCT = 'shop/SHOP_INIT_LIST_PRODUCT';
export const SHOP_RESET_LIST_PRODUCT = 'shop/SHOP_RESET_LIST_PRODUCT';