export const PRODUCTDETAIL_REQUEST = 'PRODUCTDETAIL_REQUEST';
export const PRODUCTDETAIL_SUCCESS = 'PRODUCTDETAIL_SUCCESS';
export const PRODUCTDETAIL_FAILED = 'PRODUCTDETAIL_FAILED';
export const PRODUCTDETAIL_CHANGE_PRODUCTAVATAR = 'PRODUCTDETAIL_CHANGE_PRODUCTAVATAR';
export const UPDATE_LIST_COMMENT = 'UPDATE_LIST_COMMENT';
