export const GET_LIST_PRODUCT_CART = "CART/GET_LIST_PRODUCT_CART";
export const ADD_PRODUCT_CART = "CART/ADD_PRODUCT_CART";
export const UPDATE_PRODUCT_CART = "CART/UPDATE_PRODUCT_CART";
export const UNDO_PRODUCT_CART = "CART/UNDO_PRODUCT_CART";
export const REMOVE_PRODUCT_CART = "CART/REMOVE_PRODUCT_CART";
export const CLOSE_CART = "CART/CLOSE_CART";