export const GET_LIST_KEYWORD_REQUEST = 'keyword/GET_LIST_KEYWORD_REQUEST';
export const GET_LIST_KEYWORD_SUCCESS = 'keyword/GET_LIST_KEYWORD_SUCCESS';
export const GET_LIST_KEYWORD_FAILED = 'keyword/GET_LIST_KEYWORD_FAILED';