export const GET_ACCOUNT_PRODUCT_REQUEST = 'AccountListProduct/GET_ACCOUNT_PRODUCT_REQUEST';
export const GET_ACCOUNT_PRODUCT_SUCCESS = 'AccountListProduct/GET_ACCOUNT_PRODUCT_SUCCESS';
export const GET_ACCOUNT_PRODUCT_FAILED = 'AccountListProduct/GET_ACCOUNT_PRODUCT_FAILED';
